LANGUAGE = {
    "en": {
        "language": "Language:",
        "username": "Username:",
        "password": "Password:",
        "username_placeholder_input": "Enter your username",
        "password_placeholder_input": "Enter your password",
        "log_in": "Log In",
        "wrong_pass": "Wrong Password",
        "wrong_pass_text": "Your password is wrong",
        "user_no": "Non-existent user",
        "fail_user": "The user doesn't exists",
        "create_lobby": "Create Lobby",
        "join_lobby": "Join Lobby",
        "leaderboards": "Leaderboards",
        "exit": "Exit",
        "menu": "Menu",
        "name": "Name:",
        "name_ph": "Enter the lobby's name",
        "password_ph": "Enter the lobby's password",
        "back": "Back",
        "create": "Create",
        "create_lobby": "Create Lobby",
        "choose": "Choose your side!",
        "play": "Play!",
        "story": "Story",
        "video": "resources/vid_english.mp4",
        "confirm_pass": "Confirm password:",
        "add_user": "Add user",
        "add_users": "Add users",
        "admin": "Administration",
        "log_out": "Log out",
        "search_users": "Search users",
        "game_lobbies": "Game lobbies",
        "inv_username": "Invalid username",
        "user_not_long": "Your username must be more than 4 characters",
        "inv_pass": "Invalid password",
        "pass_not_long": "Your password must be more than 8 characters",
        "other_name": "Choose other username",
        "existing_user": "This Username already exists",
        "registered": "Player registered!",
        "welcome": "Welcome to The Project Laika!",
        "pass_problem": "Password problem",
        "pass_dont_match": "Your passwords don't match",
        "del_user": "Delete",
        "del_info": "Are you sure you want to delete the selected user?",
        "ok": "Ok",
        "yes": "Yes",
        "success": "Success!",
        "act_info": "The player's information has been updated",
        "leaderboards": "Leaderboards",
        "player": "Player",
        "score": "Score",
        "set_ships": "Set the ships",
        "upright": "Upright",
        "horizontal": "Horizontal",
        "ships": "Ships",
        "rotate": "Press me to rotate",
        "clear_button": "Clear board",
        "ready": "Ready!",
        "time_remaining": "Time remaining:",
        "search": "Search",
        "change_pass": "Change password",
        "edit_pass": "Change player's password",
        "new_pass": "Enter a new password",
        "save": "Save",
        "cancel": "Cancel",
        "delete": "Delete",
        "user_header": "Player's list",
        "against": "Battle against:",
        "attack": "ATTACK!",
        "error": "Error",
        "inf_error": "There's something wrong, please try later",
        "lobby_name": "Invalid lobby's name",
        "lobby_desc": "The lobby's name must be more than 4 characters",
        "lobby_exist": "The lobby's name already exists",
        "lobbies": "Lobbies",
        "full_lobby_tittle": "Full lobby",
        "full_lobby_message": "This lobby is full, try a different one",
        "spiderman": "resources/waiting_english.jpg",
        "waiting": "Waiting for the other player...",
        "game": "Game",
        "wrong_ip": "Please enter a valid IP",
        "wrong_ip_title": "Wrong IP",
        "ip_address": "IP address:",
        "win_title": "You're the Winner!",
        "win_text": "Congratulations! You win the game!",
        "lose_title": "You lose...",
        "lose_text": "You lose the game :(",
        "return_to_menu": "Close game",
    },
    "es": {
        "language": "Idioma:",
        "username": "Nombre de usuario:",
        "password": "Contraseña:",
        "username_placeholder_input": "Ingresa tu nombre de usuario",
        "password_placeholder_input": "Ingresa tu contraseña",
        "log_in": "Iniciar sesión",
        "wrong_pass": "Contraseña incorrecta",
        "wrong_pass_text": "Tu contraseña es incorrecta",
        "user_no": "El usuario no existe",
        "fail_user": "El nombre de usuario ingresado no está registrado",
        "create_lobby": "Crear sala",
        "join_lobby": "Unirse a sala",
        "leaderboards": "Mejores jugadores",
        "exit": "Salir",
        "menu": "Menú",
        "name": "Nombre:",
        "name_ph": "Ingresa el nombre de la sala",
        "password_ph": "Ingresa la contraseña de la sala",
        "back": "Volver",
        "create": "Crear",
        "create_lobby": "Crear Sala",
        "choose": "¡Escoge tu bando!",
        "play": "¡Jugar!",
        "story": "Historia",
        "video": "resources/vid_spanish.mp4",
        "confirm_pass": "Confirmar contraseña:",
        "add_user": "Agregar usuario",
        "add_users": "Agregar usuarios",
        "admin": "Administración",
        "log_out": "Cerrar sesión",
        "search_users": "Buscar usuarios",
        "game_lobbies": "Salas de juego",
        "inv_username": "Nombre de usuario inválido",
        "user_not_long": "Tu nombre de usuario debe de contener más de 4 caracteres",
        "inv_pass": "Contraseña inválida",
        "pass_not_long": "Tu contraseña debe de contener más de 8 caracteres",
        "other_name": "Selecciona otro nombre de ususario",
        "existing_user": "Ese nombre de usuario ya existe",
        "registered": "¡Jugador registrado!",
        "welcome": "¡Bienvenido a Project Laika!",
        "pass_problem": "Hay un problema con la contraseña",
        "pass_dont_match": "Las contraseñas no coinciden",
        "del_user": "Eliminar",
        "del_info": "¿Seguro que desea eliminar al usuario seleccionado?",
        "ok": "De acuerdo",
        "yes": "Sí",
        "success": "¡Éxito!",
        "act_info": "La información del jugador ha sido actualizada",
        "leaderboards": "Mejores jugadores",
        "player": "Jugador",
        "score": "Récord",
        "set_ships": "Posiciona las naves",
        "upright": "Vertical",
        "horizontal": "Horizontal",
        "ships": "Naves",
        "rotate": "Presiónmae para rotar",
        "clear_button": "Limpiar el tablero",
        "ready": "¡Listo!",
        "time_remaining": "Tiempo restante:",
        "search": "Buscar",
        "change_pass": "Cambiar contraseña",
        "edit_pass": "Cambiar la contraseña del jugador",
        "new_user": "Ingresa un nuevo nombre de usuario",
        "new_pass": "Ingresa una nueva contraseña",
        "save": "Guardar",
        "cancel": "Cancelar",
        "delete": "Eliminar",
        "user_header": "Lista de jugadores",
        "against": "Batalla contra:",
        "attack": "¡ATACAR!",
        "error": "Error",
        "inf_error": "Ha pasado algo mal, intente de nuevo más tarde",
        "lobby_name": "Nombre de lobby inválido",
        "lobby_desc": "El nombre del lobby debe ser de más de cuatro caracteres",
        "lobby_exist": "The lobby's name already exists",
        "lobbies": "Salas",
        "full_lobby_tittle": "Sala llena",
        "full_lobby_message": "Esta sala está llena, prueba en una distinta",
        "spiderman": "resources/waiting_spanish.jpg",
        "waiting": "Esperando al otro jugador...",
        "game": "Juego",
        "wrong_ip": "Por favor ingrese una IP válida",
        "wrong_ip_title": "IP inválida",
        "ip_address": "Dirección IP:",
        "win_title": "¡Eres el ganador!",
        "win_text": "¡Felicidades!, ¡Has ganado el juego!",
        "lose_title": "Perdiste...",
        "lose_text": "Has perdido :(",
        "return_to_menu": "Cerrar juego",
    }
}